
- name: Define init host
  set_fact:
    master_bootstrap_host: "{{ groups['master'][0] }}"

- name: Get installed packages
  command: helm ls --tiller-namespace {{ helm_tiller_namespace }}
  register: r_helm_ls
  changed_when: false

- block:

  - name: Copy package values
    template: src=charts/metallb/values.yaml.j2 dest=/root/metallb-values.yaml

  - name: Install metallb Helm chart
    command: helm install --tiller-namespace {{ helm_tiller_namespace }} --name metallb --namespace {{ metallb_namespace }} -f /root/metallb-values.yaml stable/metallb

  when: '"metallb" not in r_helm_ls.stdout and inventory_hostname == master_bootstrap_host'

