# This task disables swap for Kubernetes node (see https://github.com/kubernetes/kubernetes/pull/31996)
- name: Remove swapfile from /etc/fstab
  lineinfile:
    path: /etc/fstab
    state: absent
    regexp: ".*swap.*"

- name: Disable swap
  command: swapoff -a
  changed_when: false
