- import_tasks: ../common/repo.yml
  tags: repo

- import_tasks: ../common/packages.yml
  tags: packages

- import_tasks: ../common/system.yml
  tags: system

- import_tasks: ../common/swapoff.yml
  tags: swapoff

- import_tasks: ../common/kube.yml
  tags: kube

- import_tasks: ../common/status.yml

- name: Join node to the Kubernetes cluster
  import_tasks: join.yml
  when: kubelet_up == false

- import_tasks: ../common/net.yml
  tags: net
